autoshop/autoshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from buycars.views import custom_page_not_found
from django.views.decorators.cache import never_cache
from django.conf import settings
from django.contrib.staticfiles.views import serve

handler404 = custom_page_not_found
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buycars.urls')),
    path('accounts/', include('common.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

autoshop/buycars/urls.py
from django.urls import path
from buycars.views import *
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache


app_name = 'buycars'
urlpatterns = [
    path('', index_page, name = 'index_page'),
    path('moto/', two_wheels, name = 'two_wheels'),
    path('cars/', car_list, name = 'car_list'),
    path('cars/<int:id>/', car_detail, name='car_detail'),
    path('moto/<int:id>/', moto_detail, name='moto_detail'),
    path('favorite_car/<int:car_id>/', toggle_favorite_c, name='toggle_favorite_c'),
    path('favorite_moto/<int:moto_id>/', toggle_favorite_m, name='toggle_favorite_m'),
    path('favorites_cars/', favorite_list_cars, name='favorite_list_cars'),
    path('favorites_moto/', favorite_list_moto, name='favorite_list_moto'),
    path('add-car/', add_car_ad, name='add_car_ad'),
    path('add-moto/', add_moto_ad, name='add_moto_ad'),
    path('car/<int:car_id>/edit/', edit_car, name='edit_car'),
    path('car/<int:car_id>/delete/', delete_car, name='delete_car'),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

autoshop/common/urls.py
from django.contrib.auth import views
from django.urls import path
from buycars.views import signup
from .views import edit_profile, profile, logout_view
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout_view"),
    path("signup/", signup, name="signup"),
    path('edit-profile/', edit_profile, name='edit_profile'),
    path('profile/', profile, name='profile'),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

autoshop/buycars/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.conf import settings
# Create your models here.


# class Make(models.Model):
#     name = models.CharField(
#         max_length=100, 
#         verbose_name='Марка', 
#         unique=True
#     )

#     def __str__(self):
#         return self.name
    
#     class Meta:
#         verbose_name = 'Марка транспорта'
#         verbose_name_plural = 'Марки автомобилей'
#         ordering = ['name']


# class Model(models.Model):
#     name = models.CharField(max_length=100, verbose_name='Модель')
#     make = models.ForeignKey(
#         'Make',
#         on_delete=models.CASCADE,  # Разрешено каскадное удаление
#         related_name='models', 
#         verbose_name='Марка'
#     )

#     def __str__(self):
#         return f"{self.name}"

#     class Meta:
#         unique_together = ('name', 'make')
#         verbose_name = 'Модель транспорта'
#         verbose_name_plural = 'Модели транспорта'
#         ordering = ['name']

alphanumeric_validator = RegexValidator(
    r'^[a-zA-Zа-яА-ЯёЁ\s-]*$',
    'Разрешены только буквы, пробел и дефис'
)

russian_validator = RegexValidator(
    r'^[а-яА-ЯёЁ-]*$',
    'Разрешена только кириллица и дефис'
)


class Cars(models.Model):
    conditions = (
      ('n', 'Новый'),
      ('s', 'Б/У'),
      ('p', 'На запчасти'),
    ) 

    box_type = (
      ('m', 'Механика'),
      ('a', 'Автомат'),
      ('r', 'Робот'),
    )
    fuel = (
        ('b', 'Бензин'),
        ('d', 'Дизель'),
        ('g', 'Газ'),
        ('e', 'Электричка'),
    )
    kuzov = (
        ('1', 'Седан'),
        ('2', 'Универсал'),
        ('3', 'Хетчбек'),
        ('4', 'Купе'),
        ('5', 'Лимузин'),
        ('6', 'Микроавтобус'),
        ('7', 'Минивэн'),
        ('8', 'Хардтоп'),
        ('9', 'Таун-кар'),
        ('a', 'Комби'),
        ('b', 'Лифтбек'),
        ('c', 'Фастбек'),
        ('d', 'Кабриолет'),
        ('e', 'Пикап'),
        ('f', 'Фургон'),
        ('g', 'Внедорожник')
    )

    make = models.CharField(
        max_length=40, 
        null=False, 
        blank=True, 
        verbose_name="Марка автомобиля",
        validators=[alphanumeric_validator],
    )
    model = models.CharField(
        max_length=30, 
        null=False, 
        blank=True, 
        verbose_name="Модель авто"
    )
    car_type = models.CharField(
        max_length=1, 
        choices=kuzov, 
        null = False, 
        blank = True, 
        verbose_name="Тип кузова")
    engine_volume = models.FloatField(
        null=False, 
        blank = True, 
        verbose_name="Объем двигателя")
    description = models.TextField(
        null = True, 
        blank = True, 
        verbose_name="Описание автомобиля",)
    year_of_release = models.IntegerField(
        null = False, 
        blank = True, 
        verbose_name="Год выпуска")
    published = models.DateTimeField(
        auto_now_add=True, 
        verbose_name="Дата публикации объявления")
    price = models.FloatField(
        null = False, 
        blank = True, 
        verbose_name="Цена")
    condition = models.CharField(
        max_length=1, 
        choices=conditions, 
        verbose_name="Состояние")
    transmission_box = models.CharField(
        max_length=1, 
        choices=box_type, 
        verbose_name="Коробка передач")
    color = models.CharField(
        max_length=20, 
        validators=[russian_validator],
        null=False, 
        blank=True, 
        verbose_name="Цвет авто")
    fuel_type = models.CharField(
        max_length=1, 
        choices=fuel, 
        verbose_name="Тип топлива")
    Mileage = models.IntegerField(
        null=False, 
        blank=True, 
        verbose_name='Пробег')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    # image = models.ImageField(null = False, blank = True)

    def __str__(self):
        return f'{self.make} {self.model} {str(self.year_of_release)}'
    
    def clean(self):
        if self.year_of_release < 1900 or self.year_of_release > 2025:
            raise ValidationError({'year_of_release':"Проверьте правильность ввода даты выпуска автомобиля!"})
        
        if self.Mileage < 0:
            raise ValidationError({'Mileage':"Проверьте правильность ввода пробега автомобиля!"})
        
        if self.price < 0:
            raise ValidationError({'price':"Проверьте правильность ввода цены на авто!"})
        
        if self.engine_volume > 9 or self.engine_volume < 0:
            raise ValidationError({'engine_volume':"Проверьте правильность ввода объема двигателя!"})
    
    class Meta:
        verbose_name_plural = 'Автомобили'
        verbose_name = 'Автомобиль'
        ordering = ['-published']

class Moto(models.Model):
    conditions = (
      ('n', 'Новый'),
      ('s', 'Б/У'),
      ('p', 'На запчасти'),
    )
    gear = (
        ('c', 'Цепь'),
        ('k', 'Кардан'),
        ('r', 'Ремень'),
    ) 

    make = models.CharField(
        max_length=30, 
        null=False, 
        validators=[alphanumeric_validator],
        blank=True, 
        verbose_name="Марка мотоцикла"
    )
    model = models.CharField(
        max_length=30, 
        null=False, 
        blank=True, 
        verbose_name="Модель"
    )    
    engine_volume = models.FloatField(
        null=False, 
        blank = True, 
        verbose_name="Объем двигателя в см^3")
    description = models.TextField(
        null = True, 
        blank = True, 
        verbose_name="Описание транспорта",)
    year_of_release = models.IntegerField(
        null = False, 
        blank = True, 
        verbose_name="Год выпуска")
    published = models.DateTimeField(
        auto_now_add=True, 
        verbose_name="Дата опубликования объявления")
    price = models.FloatField(
        null = False, 
        blank = True, 
        verbose_name="Цена")
    condition = models.CharField(
        max_length=1, 
        choices=conditions, 
        verbose_name="Состояние")
    main_gear = models.CharField(
        max_length=1, 
        choices=gear, 
        null=False, 
        blank=True, 
        verbose_name='Главная передача')
    color = models.CharField(
        max_length=20, 
        null=False, 
        validators=[russian_validator],
        blank=True, 
        verbose_name="Цвет транспорта")
    Mileage = models.IntegerField(
        null=False, 
        blank=True, 
        verbose_name='Пробег',)


    # image = models.ImageField(null = False, blank = True)

    def __str__(self):
      return f"{self.make} {self.model} {str(self.engine_volume)}"

    class Meta:
        verbose_name_plural = 'Мотоциклы'
        verbose_name = 'Мотоцикл'
        ordering = ['-published']

class Profile(AbstractUser):
    # user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=15, verbose_name='Номер телефона', blank=True)
    is_seller = models.BooleanField(default=False, verbose_name='Продавец?')

    def clean(self):
        if not self.phone.startswith('+375'):
            raise ValidationError('Номер должен начинаться с "+375" (Беларусь)')

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = 'Пользователи'
        verbose_name = 'Пользователь'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Favorite(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Пользователь"
    )
    car = models.ForeignKey(
        'Cars',
        on_delete=models.CASCADE,
        verbose_name="Автомобиль"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата добавления"
    )

    class Meta:
        unique_together = ('user', 'car')
        verbose_name = 'Список избранных автомобилей'
        verbose_name_plural = 'Избранные авто'

    def __str__(self):
        return f"{self.user.username} - {self.car}"
    
class Favorite_moto(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name="Пользователь"
    )
    moto = models.ForeignKey(
        'Moto',
        on_delete=models.CASCADE,
        verbose_name="Мотоцикл"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата добавления"
    )

    class Meta:
        unique_together = ('user', 'moto')
        verbose_name = 'Список избранных мотоциклов'
        verbose_name_plural = 'Избранные мотоциклы'

    def __str__(self):
        return f"{self.user.username} - {self.moto}"

autoshop/buycars/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from django.contrib.auth.decorators import login_required
from .models import Cars, Moto, Favorite, Favorite_moto
from .forms import SignUpForm, CarAdForm, CarForm
from django.http import JsonResponse
from .models import Favorite, Favorite_moto
from .forms import CarAdForm, MotoAdForm
from django.contrib.auth import login
from django.core.exceptions import PermissionDenied

@login_required
def edit_car(request, car_id):
    car = get_object_or_404(Cars, id=car_id, owner=request.user)  
    
    if request.method == 'POST':
        form = CarForm(request.POST, instance=car)
        if form.is_valid():
            form.save()
            return redirect('buycars:car_detail', id=car.id)
    else:
        form = CarForm(instance=car)
    
    return render(request, 'registration/edit_car.html', {
        'form': form,
        'car': car 
    })

@login_required
def delete_car(request, car_id):
    car = get_object_or_404(Cars, id=car_id)
    if car.owner != request.user:
        raise PermissionDenied
    car.delete()
    return redirect('buycars:car_list')

def index_page(request):
    return render(request, "buycars/index.html")

def car_list(request):
    queryset = Cars.objects.all()

    sort_by = request.GET.get('sort', '')

    if sort_by == 'date_asc':
        queryset = queryset.order_by('published')  
    elif sort_by == 'date_desc':
        queryset = queryset.order_by('-published')  
    elif sort_by == 'price_asc':
        queryset = queryset.order_by('price') 
    elif sort_by == 'price_desc':
        queryset = queryset.order_by('-price') 
    elif sort_by == 'name_asc':
        queryset = queryset.order_by('make', 'model') 
    elif sort_by == 'name_desc':
        queryset = queryset.order_by('-make', '-model')  

    context = {
        'vehicles': queryset,
    }
    return render(request, 'buycars/cars.html', context)


def two_wheels(request):
    queryset = Moto.objects.all()

    sort_by = request.GET.get('sort', '')

    if sort_by == 'date_asc':
        queryset = queryset.order_by('published')  
    elif sort_by == 'date_desc':
        queryset = queryset.order_by('-published')  
    elif sort_by == 'price_asc':
        queryset = queryset.order_by('price') 
    elif sort_by == 'price_desc':
        queryset = queryset.order_by('-price') 
    elif sort_by == 'name_asc':
        queryset = queryset.order_by('make', 'model') 
    elif sort_by == 'name_desc':
        queryset = queryset.order_by('-make', '-model')  

    context = {
        'half_car': queryset
    }
    return render(request, 'buycars/moto.html', context)


def car_detail(request, id):
    car = get_object_or_404(Cars, id=id)
    return render(request, 'buycars/details_car.html', {'car': car})

def moto_detail(request, id):
    moto = get_object_or_404(Moto, id=id)
    return render(request, 'buycars/details_moto.html', {'moto': moto})

def custom_page_not_found(request, exception):
    return render(request, 'buycars/404.html', status=404)


@login_required
def add_car_ad(request):
    if not request.user.is_seller:
        return redirect('buycars:index_page') 
    
    if request.method == 'POST':
        form = CarAdForm(request.POST, request.FILES)
        if form.is_valid():
            car = form.save(commit=False)
            car.owner = request.user
            car.save()
            return redirect('buycars:car_detail', id=car.id)
    else:
        form = CarAdForm()
    
    return render(request, 'registration/add_car_ad.html', {'form': form})

@login_required
def add_moto_ad(request):
    if not request.user.is_seller:
        return redirect('index_page')
    
    if request.method == 'POST':
        form = MotoAdForm(request.POST, request.FILES)
        if form.is_valid():
            moto = form.save(commit=False)
            moto.seller = request.user
            moto.save()
            return redirect('buycars:moto_detail', id=moto.id)
    else:
        form = MotoAdForm()
    
    return render(request, 'registration/add_moto_ad.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('buycars:index_page')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


@login_required
def toggle_favorite_c(request, car_id):
    car = get_object_or_404(Cars, id=car_id)
    favorite, created = Favorite.objects.get_or_create(user=request.user, car=car)
    
    if not created:
        favorite.delete()
        is_favorite = False
    else:
        is_favorite = True
    
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({'is_favorite': is_favorite})
    
    return redirect(request.META.get('HTTP_REFERER', 'cars:list'))

@login_required
def toggle_favorite_m(request, moto_id):
    moto = get_object_or_404(Moto, id=moto_id)
    favorite, created = Favorite_moto.objects.get_or_create(user=request.user, moto=moto)
    
    if not created:
        favorite.delete()
        is_favorite = False
    else:
        is_favorite = True
    
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        return JsonResponse({'is_favorite': is_favorite})
    
    return redirect(request.META.get('HTTP_REFERER', 'moto:list'))

@login_required
def favorite_list_moto(request):
    favorites = Favorite_moto.objects.filter(user=request.user).select_related('moto')
    return render(request, 'registration/favorite_list.html', {'favorites': favorites, 'type':'moto'})

@login_required
def favorite_list_cars(request):
    favorites = Favorite.objects.filter(user=request.user).select_related('car')
    return render(request, 'registration/favorite_list.html', {'favorites': favorites, 'type':'car'})

autoshop/buycars/templates/buycars/cars.html
{% extends "registration/base.html" %}
{% load static %}

{% block title %}Autoshop - Машины{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'buycars/css/stylevehicles.css' %}">

    <h1>Список доступных автомобилей</h1>
    {% if request.user.is_authenticated %}
        <a href="{% url 'buycars:favorite_list_cars' %}" class="fav" type='car'>Список избранных автомобилей</a>
    {% endif %}
    {% if user.is_authenticated and user.is_seller %}
        <a href="{% url 'buycars:add_car_ad' %}" class="btn">Создать объявление</a>
    {% endif %}

    <form method="get" action="{% url 'buycars:car_list' %}" class="sort-form">
        <label for="sort">Сортировать по:</label>
        <select name="sort" id="sort">
            <option value="date_desc">Дата публикации (сначала новые)</option>
            <option value="date_asc">Дата публикации (сначала старые)</option>
            <option value="price_asc">Цена (по возрастанию)</option>
            <option value="price_desc">Цена (по убыванию)</option>
            <option value="name_asc">Название (А-Я)</option>
            <option value="name_desc">Название (Я-А)</option>
        </select>
        <button type="submit">Применить</button>
    </form>

    <ul>
        {% for car in vehicles %}
            <li>
                <a href="{% url 'buycars:car_detail' id=car.id %}"> {{ car.make }} {{ car.model }} - {{ car.price }} у.е </a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'buycars:index_page' %}" class="btn-back">Назад</a>
{% endblock %}

autoshop/buycars/templates/buycars/details_car.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autoshop</title>
    <link rel="stylesheet" href="{% static 'buycars/css/car_details_style.css'%}"> 
</head>
<body>
    <img src="{% static 'buycars/img/logo.png' %}" class="logotip">
    <div class="container">
        <h1>Autoshop</h1>
        <div class="car-details">
            <h2> {{car.make}} {{car.model}}</h2>
            <p><strong>Тип кузова:</strong> {{car.get_car_type_display}}</p>
            <p><strong>Объем двигателя:</strong> {{car.engine_volume}} л.</p>
            <p><strong>Коробка передач:</strong> {{car.get_transmission_box_display}}</p>
            <p><strong>Год выпуска:</strong> {{car.year_of_release}}</p>
            <p><strong>Пробег:</strong> {{car.Mileage}} км</p>
            <p><strong>Состояние:</strong> {{car.get_condition_display}}</p>
            <p><strong>Тип топлива:</strong> {{car.get_fuel_type_display}}</p>
            <p><strong>Цвет:</strong> {{car.color}}</p>
            <p><strong>Цена:</strong> {{car.price}} у.е</p>
            <p>Создано {{ car.published }}</p>
        </div>

        <div class="car-details">
            <h2>Описание</h2>
            <p>{{ car.description }}</p>
        </div>
    <a href="{% url 'buycars:toggle_favorite_c' car.id %}" class="favorite-btn" data-car-id="{{ car.id }}">
        {% if user.is_authenticated and car.id in user_favorite_ids %}
            ★
        {% else %}
            ☆
        {% endif %}
    </a>
    
        <a href="{% url 'buycars:car_list' %}" class="back-btn">Назад</a>
        {% if user == car.owner %}
            <div class="owner-actions">
                <a href="{% url 'buycars:edit_car' car.id %}" class="btn">Редактировать</a>
                <a href="{% url 'buycars:delete_car' car.id %}" class="btn btn-danger">Удалить</a>
            </div>
        {% endif %}
    </div>
</body>
<script src="{% static 'buycars/js/knopki.js' %}"></script>
</html>

autoshop/buycars/templates/buycars/details_moto.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autoshop</title>
    <link rel="stylesheet" href="{% static 'buycars/css/moto_details_style.css'%}">
</head>
<body>
    <img src="{% static 'buycars/img/logo.png' %}" class="logotip">

    <div class="container">
        <h1>Описание автомобиля</h1>

        <div class="car-details">
            <h2>{{ moto.make }} {{ moto.model }}</h2>
            <p><strong>Объем двигателя:</strong> {{ moto.engine_volume }} см^3</p>
            <p><strong>Главная передача:</strong> {{ moto.get_main_gear_display }}</p>
            <p><strong>Год выпуска:</strong> {{ moto.year_of_release }}</p>
            <p><strong>Пробег:</strong> {{ moto.Mileage }} км</p>
            <p><strong>Состояние:</strong> {{ moto.get_condition_display }}</p>
            <p><strong>Цвет:</strong> {{ moto.color }}</p>
            <p><strong>Цена:</strong> {{ moto.price }} у.е</p>
            <p>Создано {{ moto.published }}</p>
        </div>

        <div class="car-details">
            <h2>Описание</h2>
            <p>{{ moto.description }}</p>
        </div>
        {% if request.user.is_authenticated %}
            <a href="{% url 'buycars:toggle_favorite_m' moto.id %}" class="favorite-btn" data-moto-id="{{ moto.id }}">
            {% if moto.id in user_favorite_ids %}
                ★
            {% else %}
                ☆
            {% endif %}
            </a>
        {% endif %}
        <a href="{% url 'buycars:two_wheels' %}" class="back-btn">Назад</a>
    </div>
</body>
<script src="{% static 'buycars/js/knopki.js' %}"></script>

</html>

autoshop/buycars/templates/buycars/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autoshop</title>
    <link rel="stylesheet" href="{% static 'buycars/css/style.css' %}">
</head>
<body>
    <header>
        <div class="container2">
            <img src="{% static 'buycars/img/logo.png' %}" class="logotip">
            {% if user.is_authenticated %}
                <div class="auth-message">
                    <p>Здравствуйте, {{ user.username }}! <a href="{% url 'profile' %}" class="btn">Профиль</a></p>
                    <p><a href="{% url 'logout_view' %}" class="btn">Выйти</a></p>
                </div>
            {% else %}
                <div class="auth-links">
                    <a href="{% url 'login' %}" class="btn">Войти</a>
                    <a href="{% url 'signup' %}" class="btn">Зарегистрироваться</a>
                </div>
            {% endif %}
            <h1>Начните выбор транспорта мечты прямо сейчас!</h1>
            <nav>
                <ul>
                    <li><a href="{% url 'buycars:two_wheels' %}" class="btn">Мотоциклы</a></li>
                    <li><a href="{% url 'buycars:car_list' %}" class="btn">Автомобили</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <main class="container">
        <section>
            <h2>О нас</h2>
            <p>Мы предлагаем лучший выбор мотоциклов и автомобилей. Просто, удобно, доступно.</p>
        </section>
    </main>

    <footer>
        <div class="container">
            <p>&copy; Кветинский Матвей Corporated</p>
        </div>
    </footer>
</body>
</html>

autoshop/buycars/templates/buycars/moto.html
{% extends "registration/base.html" %}
{% load static %}

{% block title %}Autoshop - Мотоциклы{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'buycars/css/stylevehicles.css' %}">

    <h1>Список доступных мотоциклов:</h1>
    {% if request.user.is_authenticated %}
        <a href="{% url 'buycars:favorite_list_moto' %}" class="fav" type='moto'>Список избранных мотоциклов</a>
    {% endif %}
    {% if user.is_authenticated and user.is_seller %}
        <a href="{% url 'buycars:add_moto_ad' %}" class="btn">Создать объявление</a>
    {% endif %}

    <form method="get" action="{% url 'buycars:two_wheels' %}" class="sort-form">
        <label for="sort">Сортировать по:</label>
        <select name="sort" id="sort">
            <option value="date_desc">Дата публикации (сначала новые)</option>
            <option value="date_asc">Дата публикации (сначала старые)</option>
            <option value="price_asc">Цена (по возрастанию)</option>
            <option value="price_desc">Цена (по убыванию)</option>
            <option value="name_asc">Название (А-Я)</option>
            <option value="name_desc">Название (Я-А)</option>
        </select>
        <button type="submit">Применить</button>
    </form>

    <ul>
        {% for moto in half_car %}
            <li>
                <a href="{% url 'buycars:moto_detail' id=moto.id %}">{{ moto.make }} {{ moto.model }} - {{ moto.price }} у.е</a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'buycars:index_page' %}" class="btn-back">Назад</a>
{% endblock %}